In [3]:
import pandas as pd
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split


SF_listings_file = '/Users/alihanisar/Downloads/listingsSF.csv'
SFlistingsdata = pd.read_csv(SF_listings_file)
SFlistingsdata.describe()
SFlistingsdata.shape

SFlistingsdata = SFlistingsdata [["neighbourhood","latitude","longitude","room_type","price","minimum_nights","reviews_per_month"]]
SFlistingsdata.head()
SFlistingsdata = SFlistingsdata.dropna()
SFlistingsdata

y = SFlistingsdata.price

SFlistings_features = ["neighbourhood","room_type"]
X = pd.get_dummies(SFlistingsdata[SFlistings_features])

train_X, val_X, train_y, val_y = train_test_split( X , y , random_state=0 )

SFlistingsmodel = DecisionTreeRegressor(random_state=1)
SFlistingsmodel.fit(train_X , train_y)
SFmodelpredictions = SFlistingsmodel.predict(val_X)

mae = mean_absolute_error(val_y, SFmodelpredictions)
print("Decision Tree Mean Absolute Error:", mae)

SFlistingsdata.loc[val_X.index, "Predicted_price_DecisionTree"] = SFmodelpredictions



SFlistingsmodelRF = RandomForestRegressor(random_state=1)
SFlistingsmodelRF.fit(train_X , train_y)
SFmodelpredictionsRF = SFlistingsmodelRF.predict(val_X)

mae_RF = mean_absolute_error(val_y, SFmodelpredictionsRF)
print("Random Forest Mean Absolute Error:", mae_RF)

SFlistingsdata.loc[val_X.index, "Predicted_price_RandomForest"] = SFmodelpredictionsRF

SFlistingsdata

Decision Tree Mean Absolute Error: 186.54757666977963
Random Forest Mean Absolute Error: 184.30901591040407

,neighbourhood,latitude,longitude,room_type,price,minimum_nights,reviews_per_month,Predicted_price_DecisionTree,Predicted_price_RandomForest
0,Western Addition,37.770280,-122.433170,Entire home/apt,158.0,2,2.49,NaN,NaN
1,Bernal Heights,37.744740,-122.420890,Entire home/apt,235.0,30,0.57,207.068966,206.711809
2,Haight Ashbury,37.765550,-122.452130,Private room,56.0,32,0.08,NaN,NaN
3,Western Addition,37.775640,-122.436420,Entire home/apt,527.0,9,0.15,NaN,NaN
4,Bayview,37.717500,-122.396980,Private room,107.0,1,0.20,NaN,NaN
...,...,...,...,...,...,...,...,...,...
7766,Financial District,37.786260,-122.396990,Entire home/apt,430.0,30,1.00,399.580645,421.193738
7773,Marina,37.803700,-122.442630,Entire home/apt,176.0,1,1.00,NaN,NaN
7783,Western Addition,37.774960,-122.423960,Entire home/apt,486.0,1,2.00,NaN,NaN
7804,Financial District,37.794509,-122.403573,Shared room,43.0,1,4.00,NaN,NaN
7811,Marina,37.800920,-122.425813,Shared room,44.0,1,1.00,NaN,NaN